App_marketplace/App_marketplace/Ecommerce/urls.py
from django.contrib import admin
admin.autodiscover()

from django.urls import path
from . import views

app_name = "Ecommerce"
urlpatterns = [
    path("categorias/", views.categorias, name="categorias"),
    path("clientes/", views.clientes, name="clientes"),
    path("productos/", views.ProductosCreateView.as_view(), name="productos"),
]

App_marketplace/App_marketplace/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('ecommerce', include('Ecommerce.urls')),
]

App_marketplace/App_marketplace/core/urls.py
from django.urls import path
app_name = 'core'
from . import views
urlpatterns = [
    
    path('', views.home, name='home'),
]

App_marketplace/App_marketplace/Ecommerce/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
'''
    Modelo para la tabla cliente
'''

class Cliente(models.Model):
    cliente_id = models.AutoField(primary_key=True, unique=True)
    name = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    direccion = models.CharField(max_length=200)

    class Meta:
        verbose_name = "cliente"
        verbose_name_plural = "clientes"

    def __str__(self) -> str:
        return self.name + " | " + self.apellido + " | " + self.email + " | " + self.direccion
    

class Categoriaproducto(models.Model):
    categoria_id = models.AutoField(primary_key=True, unique=True)
    name = models.CharField(max_length=200)
    tipo = models.CharField(max_length=200)

    class Meta:
        
        verbose_name = "categoria"
        verbose_name_plural = "categorias"

    def __str__(self):
        return self.name + " | " + self.tipo

    def get_absolute_url(self):
        return reverse("categoria_detail", kwargs={"pk": self.pk})


class Producto(models.Model):
    producto_id = models.AutoField(primary_key=True, unique=True)
    name = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.TextField()
    categoria_id = models.ForeignKey("categoriaproducto", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "productos"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("producto_detail", kwargs={"pk": self.pk})


class Delivery(models.Model):
    delivery_id = models.AutoField(primary_key=True, unique=True)
    tipo = models.CharField(max_length=200)
    estatus = models.CharField(max_length=200)

    class Meta:
        verbose_name = "delivery"
        verbose_name_plural = "deliveries"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("delivery_detail", kwargs={"pk": self.pk})


class Pedido(models.Model):
    pedido_id = models.AutoField(primary_key=True, unique=True)
    date = models.DateTimeField()
    status = models.CharField(max_length=200)
    delivery_id = models.ForeignKey("Delivery", on_delete=models.CASCADE)
    cliente_id = models.ForeignKey("Cliente", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "pedido"
        verbose_name_plural = "pedidos"

    def __str__(self):
        return self.status

    def get_absolute_url(self):
        return reverse("pedido_detail", kwargs={"pk": self.pk})

App_marketplace/App_marketplace/core/models.py
from django.db import models

# Create your models here.

App_marketplace/App_marketplace/Ecommerce/forms.py
from django.contrib.admin.widgets import AutocompleteSelect
from django import forms

from .admin import admin
from .models import Categoriaproducto,  Producto, Cliente

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoriaproducto
        fields = ('name', 'tipo')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'type': 'text'
        })
        self.fields['tipo'].widget.attrs.update({
            'class': 'form-control',
            'type': 'text'
        })

class ProductosForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields =    ("name", "precio", "descripcion","categoria_id")
        
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "precio": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
            "categoria_id":forms.Select(attrs={"class": "form-select mb-3"}) 
        }
            

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ('name', 'apellido', 'email', 'direccion')

        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "apellido": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.TextInput(attrs={"class": "form-control"}),
            "direccion": forms.TextInput(attrs={"class": "form-control"}),
        }

App_marketplace/App_marketplace/Ecommerce/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from . import models, forms
from django.views.generic import CreateView
from django.views.generic import ListView


# Create your views here.


def categorias(request):
    query = models.Categoriaproducto.objects.all()
    if request.method == "POST":
        form = forms.CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Ecommerce:categorias')
    else:
        form = forms.CategoriaForm()
    contexto = {"categorias":query,"form": form}
    return render(request, "ecommerce/categorias.html", contexto)

def productos(request):

    pruductos = models.Producto.objects.all()
    contexto= {'productos': pruductos}

    return render(request, "ecommerce/productos.html", contexto)

def clientes(request):
    query = models.Cliente.objects.all()
    if request.method == "POST":
        form = forms.ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Ecommerce:clientes')
    else:
        form = forms.ClienteForm()
    contexto = {"clientes":query,"form": form}
    return render(request, "ecommerce/clientes.html", contexto)

class ProductosCreateView(CreateView):
    model = models.Producto
    template_name = "ecommerce/productos.html"
    form_class = forms.ProductosForm
    success_url = '.'
    


class ClientesList(ListView):
    model = models.Cliente

App_marketplace/App_marketplace/core/views.py
from django.shortcuts import render
from Ecommerce.models import Categoriaproducto
# Create your views here.
def home(request):
    categoria = Categoriaproducto.objects.all()
    contexto= {'categorias': categoria}
    return render(request, 'core/index.html', contexto)

App_marketplace/App_marketplace/Ecommerce/templates/Ecommerce/buscarcategoria.html
{% extends 'core/base.html' %}

{% block contenido %}

<div class="col-sm-12 col-xl-10 mt-5">
    <div class="bg-light rounded h-100 p-4">

        <div class="row">
            <div class="col-sm-10 col-md-6 pt-4">
                <h6 class="mb-4">Listado de Categorias</h6>

            </div>
            <div class="col-sm-10 col-md-6">
                <form method="get">
                    
                        <label>Buscar: <input type="search" id= "categoria" name="categoria" class="form-control form-control-sm" placeholder=""
                            aria-controls="key-datatable"> </label>
                        <button type="submit" class="btn btn-primary">Buscar</button>
                        
                    
                </form>
                
                
            </div>

        </div>

        <div class="mt-2">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Tipo Categoria</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in categorias %}
                    <tr>
                        <td>{{ category.categoria_id }}</td>
                        <td>{{ category.name }}</td>
                        <td>{{ category.tipo }}</td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
    </div>

</div>

{% endblock contenido %}

App_marketplace/App_marketplace/Ecommerce/templates/Ecommerce/categorias.html
{% extends 'core/base.html' %}
{% block nav_item_about %}active{% endblock nav_item_about %}
{% block contenido %}

<div class="col-sm-12 col-xl-10 mt-5">
    <form method="post" action="">
        {% csrf_token %}
        <div class="bg-light rounded h-100 p-4">
            <h6 class="mb-4">Agregar Categoria</h6>
            <div class="mb-3">
                <label class="form-label">Nombre Categoria</label>
                {{ form.name}}
            </div>

            <div class="mb-3">
                <label class="form-label">Tipo Categoria</label>
                {{ form.tipo}}
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </form>
</div>


<div class="col-sm-12 col-xl-10 mt-5">
    <div class="bg-light rounded h-100 p-4">
        <div class="row">
            <div class="col-sm-10 col-md-6 pt-4">
                <h6 class="mb-4">Listado de Categorias</h6>
            </div>
            <div class="col-sm-10 col-md-6">
                <form method="get">
                    <input type="text" name="consulta" class="form-control form-control-sm" placeholder="Buscar.."
                        aria-controls="key-datatable">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </form>
            </div>
        </div>
        <div class="mt-2">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Tipo Categoria</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in categorias %}
                    <tr>
                        <td>{{ category.categoria_id }}</td>
                        <td>{{ category.name }}</td>
                        <td>{{ category.tipo }}</td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
    </div>

</div>

{% endblock contenido %}

App_marketplace/App_marketplace/Ecommerce/templates/Ecommerce/clientes.html
{% extends 'core/base.html' %}

{% block contenido %}


<div class="col-sm-12 col-xl-10 mt-5">
    <form method="post" action="">
        {% csrf_token %}
        <div class="bg-light rounded h-100 p-4">
            <h6 class="mb-4">Crear Cliente</h6>
            <div class="mb-3">
                <label class="form-label">Nombre:</label>
                {{ form.name}}
            </div>
            <div class="mb-3">
                <label class="form-label">Apellido:</label>
                {{ form.apellido}}
            </div>
            <div class="mb-3">
                <label class="form-label">Email:</label>
                {{ form.email}}
            </div>
            <div class="mb-3">
                <label class="form-label">Dirección Envios:</label>
                {{ form.direccion}}
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>

        </div>

    </form>
</div>


<div class="col-sm-12 col-xl-10 mt-5">
    <div class="bg-light rounded h-100 p-4">

        <div class="row">
            <div class="col-sm-10 col-md-6 pt-4">
                <h6 class="mb-4">Listado de Categorias</h6>

            </div>
            <div class="col-sm-10 col-md-6">
                <form method="get">

                    <input type="text" name="consulta" class="form-control form-control-sm" placeholder="Buscar.."
                        aria-controls="key-datatable">
                    <button type="submit" class="btn btn-primary">Buscar</button>


                </form>


            </div>

        </div>

        <div class="mt-2">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Tipo Categoria</th>
                    </tr>
                </thead>
                <tbody>
                    {% for client in clientes %}
                    <tr>
                        <td>{{ client.cliente_id }}</td>
                        <td>{{ client.name }}</td>
                        <td>{{ client.apellido }}</td>
                        <td>{{ client.email }}</td>
                        <td>{{ client.direccion }}</td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
    </div>

</div>

{% endblock contenido %}

App_marketplace/App_marketplace/Ecommerce/templates/Ecommerce/productos.html
{% extends 'core/base.html' %}
{% block contenido %}

<div class="col-sm-12 col-xl-10 mt-5">
    <form method="post" action="">
        {% csrf_token %}
        <div class="bg-light rounded h-100 p-4">
            <h6 class="mb-4">Agregar Producto</h6>
            <div class="mb-3">
                <label class="form-label">Nombre:</label>
                {{ form.name}}
            </div>
            <div class="mb-3">
                <label class="form-label">Precio:</label>
                {{ form.precio}}
            </div>
            <div class="mb-3">
                <label class="form-label">Descripcion:</label>
                {{ form.descripcion}}
            </div>
            <div class="mb-3">
                <label class="form-label">Categoria:</label>
                {{ form.categoria_id}}
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            </div>

        
    </form>
</div>


<div class="col-sm-12 col-xl-10 mt-5">
    <div class="bg-light rounded h-100 p-4">

        <div class="row">
            <div class="col-sm-10 col-md-6 pt-4">
                <h6 class="mb-4">Listado de Productos</h6>

            </div>
            <div class="col-sm-10 col-md-6">
                <form method="get">
                    
                    <input type="text" name="consulta" class="form-control form-control-sm" placeholder="Buscar.."
                    aria-controls="key-datatable">
                        <button type="submit" class="btn btn-primary">Buscar</button>
                        
                    
                </form>
                
                
            </div>

        </div>

        <div class="mt-2">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Descripción</th>
                        <th scope="col">Categoria</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pro in productos %}
                    <tr>
                        <td>{{ pro.producto_id }}</td>
                        <td>{{ pro.name }}</td>
                        <td>{{ pro.precio }}</td>
                        <td>{{ pro.descripcion }}</td>
                        <td>{{ pro.categoria_id }}</td>
                       
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
    </div>

</div>



{% endblock contenido %}

App_marketplace/App_marketplace/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    {% block tittle %}
    <title>Administración Marketplace</title>
    {% endblock tittle %}
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <!-- Libraries Stylesheet -->
    <link href="{% static 'core/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />
    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Template Stylesheet -->
    <link href="{% static 'core/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">

        {% include 'core/components/navbar.html' %}

        <!-- Content Start -->
        <div class="content">

            <div class="m-4">
                {% block contenido %}
                {% endblock contenido %}
            </div>


            {% include 'core/components/footer.html' %}

        </div>
        <!-- Content End -->

    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'core/lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'core/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'core/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'core/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'core/lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'core/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'core/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Template Javascript -->
    <script src="{% static 'core/js/main.js' %}"></script>
</body>

</html>

App_marketplace/App_marketplace/core/templates/core/components/buscar.html
<div class=" d-none d-md-block">
    <a href="index.html" class="d-flex d-lg-none me-4">
        <h2 class="text-primary mb-0"><i class="fa fa-home"></i></h2>
    </a>
    <form class="d-none d-md-flex ms-4">
        <input class="form-control border-0" type="search" placeholder="Buscar">
        <button type="submit" class="btn btn-success m-2"> Buscar</button>
    </form>

</div>

App_marketplace/App_marketplace/core/templates/core/components/footer.html
 <!-- Footer Start -->

 {% comment  %}
 <div class="pt-0 px-0 fixed-bottom">
    <div class="bg-light rounded-top p-4">
        <div class="row">
            <div class="col-12 col-sm-6 text-center text-sm-start">
                &copy; <a href="#">Blue Shop</a>, All Right Reserved. 
            </div>
            <div class="col-12 col-sm-6 text-center text-sm-end">
                <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                Designed By <a href="https://htmlcodex.com">HTML Codex</a>
            </br>
            Distributed By <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
            </div>
        </div>
    </div>
</div>
 {% endcomment %}

<!-- Footer End -->

App_marketplace/App_marketplace/core/templates/core/components/navbar.html
<!-- Sidebar Start -->
{% load static %}
<div class="sidebar pe-2 pb-2">
    <nav class="navbar bg-light navbar-light">
        <a href="index.html" class="navbar-brand mx-4 mb-3">
            <h3 class="text-primary text-lg-start ">Blue Shop</h3>

        </a>
        <div class="d-flex align-items-center ms-4 mb-4">
            <div class="position-relative">

                <img class="rounded-circle" src="{% static 'core/img/user.jpg' %}" alt=""
                    style="width: 40px; height: 40px;">
                <div
                    class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1">
                </div>
            </div>
            <div class="ms-3">
                <h6 class="mb-0">Andrés Duque</h6>
                <span>Administrador</span>
            </div>
        </div>
        <div class="navbar-nav w-100">
            <a href="{% url 'core:home' %}" class="nav-item nav-link active"><i class="fa fa-home me-2"></i>Principal</a>
            <a href="{% url 'Ecommerce:clientes' %}" class="nav-item nav-link"><i class="fa fa-users me-2"></i>Clientes</a>
            <a href="{% url 'Ecommerce:categorias' %}" class="nav-item nav-link"><i class="fa fa-tags me-2"></i>Categorias</a>
            <a href="{% url 'Ecommerce:productos' %}" class="nav-item nav-link"><i class="fa fa-folder me-2"></i>Productos</a>
         {# <a href="chart.html" class="nav-item nav-link"><i class="fa fa-shopping-cart  me-2"></i>Pedidos</a> #}   
           {# <a href="chart.html" class="nav-item nav-link"><i class="fa fa-car me-2"></i>Delivery</a> #} 

        </div>
    </nav>
</div>
<!-- Sidebar End -->

App_marketplace/App_marketplace/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block contenido %}

<div class="col-sm-12 col-xl-10">
    <div class="bg-light rounded h-100 p-4">
        <h6 class="mb-4">Listado de Categorias</h6>
        <div class="table table-bordered">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Tipo Categoria</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in categorias %}
                    <tr>
                        <td>{{ category.categoria_id }}</td>
                        <td>{{ category.name }}</td>
                        <td>{{ category.tipo }}</td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
    </div>
</div>
{% endblock contenido %}